# ==================
# WARNING: Never store secrets or tokens in here
# They must be set via the .env file in the root directory
# ===================

# Port for the HTTP Server
quarkus.http.port=8080

# The comma separated names of the A (IPv4) record to update
azure.record-names4="@,*"

# The comma separated names of the AAAA (IPv6) record to update
azure.record-names6="@,*"